### ISSUE TITLE
Issue with download_data.py

### ISSUE THREAD

**Issue by saimn** [astropy/ccd-reduction-and-photometry-guide#227]
```
❯ python ccd-reduction-and-photometry-guide/notebooks/download_data.py
Downloading https://zenodo.org/record/3320113/files/combined_bias_100_images.fit.bz2?download=1
|=========================================================|  26M/ 26M (100.00%)         7s
Traceback (most recent call last):
  File "ccd-reduction-and-photometry-guide/notebooks/download_data.py", line 10, in <module>
    p.rename('combined_bias_100_images.fit.bz2')
  File "/home/simon/.pyenv/versions/3.7.4/lib/python3.7/pathlib.py", line 1319, in rename
    self._accessor.rename(self, target)
OSError: [Errno 18] Invalid cross-device link: '/tmp/simon/astropy-download-46280-ro2ysk3s' -> 'combined_bias_100_images.fit.bz2'
```

**Comment by mwcraig** [comment]
Closing because I think this has been fixed -- but please reopen if it is still broken for you.
